--- # ---------------
# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!
# ---------------
theme_color:
  enable: true
  main: "#49B1F5"
  paginator: "#00C4B6"
  button_hover: "#FF7242"
  text_selection: "#00C4B6"
  link_color: "#858585"
  hr_color: "#A4D8FA"
  tag_start_color: "#A4D8FA"
  tag_end_color: "#1B9EF3"

# Main menu navigation
menu:
  主页: /
  归档: /archives
  分类: /categories
  标签: /tags
  #XXX: /xxx

# Favicon
# ---------------
favicon: https://s2.ax1x.com/2019/08/07/eI1NJH.png

# PWA
# See https://github.com/JLHwung/hexo-offline
# ---------------
pwa:
  enable: false
  manifest: /manifest.json
  # If you don't want to trouble, just ignore the following things
  # See https://realfavicongenerator.net/
  # theme_color: "#49B1F5"
  # apple_touch_icon: /apple-touch-icon.png
  # favicon_32_32: /favicon-32x32.png
  # favicon_16_16: /favicon-16x16.png
  # mask_icon: /safari-pinned-tab.svg

# Highlight theme
# ---------------
highlight_theme: light

code_word_wrap: true

# Nav settings
# see the icon_name in fontawesome website.
# And you need to add the `fa` or `fab` prefix by your self.
# ---------------
social:
  github fa: https://github.com/luferl
  steam fa: https://steamcommunity.com/id/luferL
  film fa: https://space.bilibili.com/4469978

# Algolia search
# ---------------
algolia_search:
  enable: true # or false
  hits:
    per_page: 10 # the number of search results per page
  labels:
    input_placeholder: 想搜点啥
    hits_empty: "对于关键字 ${query} 啥也没找到" # if there are no result
    hits_stats: "在${time} ms内找到了${hits}篇文章"

# Local search
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/#/third-party-support?id=local-search
# ---------------
local_search:
  enable: false

# MathJax
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/#/third-party-support?id=mathjax
# ---------------
mathjax:
  enable: false
  cdn: https://cdn.jsdelivr.net/npm/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# KaTeX
# ---------------
katex:
  enable: true
  cdn:
    css: https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css

# Toggle fireworks (IE >= 10)
# ---------------
fireworks: true

# Analysis
# ---------------
baidu_analytics: e2cd7e52254704223bd3b9c0461bc06e

google_analytics: G-T5L2KPFS29

# Tencent_analytics ID
tencent_analytics:

# stylesheets loaded in the <head>
# ---------------
stylesheets:
  - /css/index.css
  # scripts loaded in the end of the body
  # ---------------
scripts:
  - /js/utils.js
  - /js/fancybox.js
  - /js/sidebar.js
  - /js/copy.js
  - /js/fireworks.js
  - /js/transition.js
  - /js/scroll.js
  - /js/head.js

  # cdn for third-party library
  # ---------------
cdn:
  css:
    fontawesome: https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
    # fontawesomeV5: https://use.fontawesome.com/releases/v5.3.1/css/all.css
  js:
    anime: https://cdn.jsdelivr.net/npm/animejs@latest/anime.min.js
    jquery: https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
    fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.js
    velocity: https://cdn.jsdelivr.net/npm/velocity-animate@latest/velocity.min.js
    velocity-ui: https://cdn.jsdelivr.net/npm/velocity-ui-pack@latest/velocity.ui.min.js

# Post info settings
# ---------------
avatar: https://s2.ax1x.com/2019/08/07/eI1UWd.jpg

top_img: https://s2.ax1x.com/2019/08/07/eI1dSA.jpg # false or url of img

post_meta:
  date_type: created # created or updated
  categories: true
  tags: true

# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/#/additional-package-support?id=word-counting
wordcount:
  enable: true

toc:
  enable: true
  number: false

post_copyright:
  enable: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/#/theme-config?id=auto-excerpt
auto_excerpt:
  enable: true
  length: 150

# slide
# For reveal.js config, see https://github.com/hakimel/reveal.js#configuration
slide:
  separator: ---
  separator_vertical: --
  charset: utf-8
  theme: black
  # optional
  mouseWheel: false
  transition: slide
  transitionSpeed: default
  parallaxBackgroundImage: ''
  parallaxBackgroundSize: ''
  parallaxBackgroundHorizontal: null
  parallaxBackgroundVertical: null

# QR_code:
# - itemlist:
#     img: https://s2.ax1x.com/2019/08/23/mBYJjf.png
#     text: 支付宝打赏
# - itemlist:
#     img: https://s2.ax1x.com/2019/08/23/mBY83t.png
#     text: 微信打赏

# adv:
# enable: false
# info:

# Share System
# ---------------
addThis:
  enable: false
#   pubid:

sharejs:
  enable: false
  disabled_sites:

# Comments System
# ---------------
disqus:
  enable: false
#   shortname: Luferl
#   count: true

# laibili:
# enable: false
# uid:

# gitment
# enable: false
# owner:
# repo:
# client_id:
# client_secret:

# gitalk:
#   enable: true
#   client_id: 4368eb3f3f6dc382fb53
#   client_secret: ce025cec79e5390f168ae3970d1c96fd7188169d
#   repo: luferl.github.io
#   owner: luferl
#   admin: luferl
#   language: zh-CN
#   js: https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js

# valine comment system. https://valine.js.org
valine:
  enable: true # if you want use valine,please set this value is ture
  appId:  VqMxq8YhQKdt87hjlDYA4UDq-MdYXbMMI
  appKey:  jMbPNFw1782lMDtEz6mIwhx4 # leancloud application app key
  notify: true # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
  verify: false # valine verify code (true/false)
  pageSize: 10 # comment list page size
  avatar: mm # gravatar style https://valine.js.org/#/avatar
  lang: zh-cn # i18n: zh-cn/en
  placeholder: 早8点-晚11点会自动发送邮件提醒 # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail #valine comment header inf

# Footer Settings
# ---------------
since: 2016

footer_custom_text: hitokoto

ICP:
  enable: false
  #text:

# busuanzi count for PV / UV in site
busuanzi:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i>
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i>
  site_pv_footer:
  # custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fa fa-file-o"></i>
  page_pv_footer:

# Sidebar Settings
# ---------------
links_title: Find me in
links:
  Github: https://github.com/luferl
  Bilibili: https://space.bilibili.com/4469978
  Steam: https://steamcommunity.com/id/luferL

  # http://esportnosave.cn/
# https://logikmeister.github.io/


# Follow Me Button
# follow:
#   enable: true
#   url: ''
#   text: ''

# Ads
# ---------------
# Google Adsense
google_adsense:
  enable: false
  js: //pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client: ca-pub-4875670030192242
  enable_page_level_ads: true

# controls the sidebar showing or hidden in different pages
sidebar_display: all # all/index/post/index-none/post-none/hidden